# AutoPilot - Example configuration file

# SELinux status
SELinux: Disabled

# List of packages to be installed
Installed_packages:
  - name: FireJail
    type: Pm
    source: firejail
  - name: Discord
    type: Pkg
    source: "https://discord.com/api/download?platform=linux&format=deb"
  - name: NVIM
    type: Sh
    source: "https://docs.alum.sh/files/NVIM-install.sh"
  - name: Chrome
    type: Pkg
    source: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - name: git
    type: Pm
    source: git

Network_Configuration:
  - nic: tun0
    ip: 192.168.2.14/24
    gateway: 192.168.2.1
    dns: 8.8.8.8,8.4.8.4
  - nic: eth0
    ip: "%DHCP%"
    gateway: "%DHCP%"
    dns: "%DHCP%"

# Shell commands to run
Run_Lines:
  - echo "Hello"
  - echo "Hello world"

# List of plugins
Plugins:
  - name: FireJail
    script: plugins/firejail
  - name: make_backup
    script: plugins/make_backup

# User management
Users:
  - name: noam
    pass: "%Gen%"
    group: sudo,noam
    shell: /bin/bash
  - name: shay
    pass: "mL{3_Ajx04,,,.......||||||//3QZ"
    group: shay
    shell: /bin/sh

# Network Configuration
Network_Configuration:
  - nic: tun0
    ip: 192.168.2.14
    gateway: 192.168.2.1
    dns: 8.8.8.8,8.4.8.4
  - nic: eth0
    ip: "%DHCP%"
    gateway: "%DHCP%"
    dns: "%DHCP%"

Environment_configuration:
  - user: noam
    config: |
      Name="Noam"
      function say_name {
        echo "This is the name: $Name"
      }
      say_name
  - user: shay
    config: |
      echo "Hello shay!"

Cronjobs:
  - user: noam
    rules: |
      * * * * * echo "$(date)" >> /home/noam-cron.txt
      * * * * * echo "sent date" >> /home/noam-cron.txt
  - user: shay
    rules: |
      * * * * * echo "$(date)" >> /home/shay-cron.txt
